### ISSUE TITLE
Installing via Bower

### ISSUE THREAD

**Issue by ivandotv** [malsup/cycle2#145]
When installing via Bower package manager, jquery.cycle2.js and jquery.cycle2.min.js are not present, all you get in the download package are the plugins.

**Comment by malsup** [comment]
Those files are not in source control, they are generated during a local build and pushed to malsup.github.com.

Try installing via url:  

```
bower install http://malsup.github.com/jquery.cycle2.js
```

**Comment by ivandotv** [comment]
That doesn't work.
If you want to install a file directly, you will need a url to the file that starts with "raw.github.com/malsup/.........

I'm curious, why registering the repository with bower, when it can't be used immediately after downloading?

**Comment by malsup** [comment]
I didn't register it.  Someone else did.

**Comment by ivandotv** [comment]
Okay, but it would be very nice if you could take care of properly registering the package.

**Comment by malsup** [comment]
How about this:

```
bower install https://raw.github.com/malsup/malsup.github.com/master/jquery.cycle2.js
```

**Comment by ivandotv** [comment]
That works.

**Comment by jamesplease** [comment]
Hey there, @malsup. It's really unfortunate that you, personally, didn't register this as a bower package, but users _will_ attempt to install this plugin from bower, as I just did. This is problematic because right now it doesn't work, as @ikixxx pointed out. And, again, it's a real shame that it was against your will, but it did happen, and if you wanted you could take a few steps to make it work for users who do use bower. I'm sure a number of people would appreciate it, myself included.

In fact, I was going to fork it to do the work for you, but there are a number of decisions that need to be made regarding making it bower compatible. If you tell me how you'd like it to be set up, I could do it. Anyway, this is what needs to be figured out:
1. The version number. You're using a versioning system that seems to work well for you, but which goes against what's quickly becoming the [industry standard](http://semver.org/). Namely, something like "1.3.0", where the first number represents a major update, the middle number represent minor updates, and the third number represents patches. Though there may not be any technical limitation forcing you to follow this syntax, the majority of other plugins do. And for that reason alone it'd be immensely useful to your users if you switched to this more standard syntax when migrating your app from your personal set of projects to the wide open world of bower.
2. Add a built file to the repository. Were this me, I'd use [grunt](http://gruntjs.com/) to include a build step in the repository, and add both the gruntfile and built file to the repo. But it's your project, so I didn't want to change it so much. Whether or not you include a build script in the repo, there would need to be a built file in the repository for it to work with bower.
3. This is a suggestion, but more organization could be beneficial. Perhaps something along the lines of `/build`, `/src`, `/plugins`, where you stick the different files in. I suggest this because of the fact that this plugin has become very sophisticated with its large amount of customization, plugins, and components, and some organization could make the repository more digestible for users trying to become acquainted with it.

I understand you have a system in place that works well for you, but it's a proprietary way of managing projects that makes it more difficult for users to jump in and get using your projects like this one. And that's a real shame, because the quality of your work is indicative of the time and effort you've put into these scripts to make them the best that they can be. I only wish for this same care to be made in making your work more widely accessible in the open-source community.

If you think it's worth your time to switch this repository over to a structure that's more bower-compatible, please let me know if I can be of any use. I'd love to do what I can to help.

Thanks!

**Comment by malsup** [comment]
@jmeas I agree and thank you for your offer to help.  I just need to carve out a little time to think about how I want to structure things.  But I already use a grunt build so it shouldn't take too much effort to reorganize.

**Comment by jamesplease** [comment]
In the meantime, you may want to [request removing it from the bower registry](https://github.com/bower/bower/issues/120). Just post the name of the package there, and they will remove it.

**Comment by dcalhoun** [comment]
I agree with @jmeas. I'd love to see jQuery Cycle2 fully Bower-fied, but requesting a removal of the current Bower package, for the time being, would be better for everyone IMO. I hit my head against a wall for awhile after installing it via Bower.

**Comment by malsup** [comment]
Just committed changes to (hopefully) get things working smoothly with Bower.  Please let me know if I messed anything up.

**Comment by jamesplease** [comment]
Things are looking a lot better, @malsup. Thanks a lot for working on this – tons of people will appreciate it, I'm sure.

One thing I'd suggest doing is adding installation instructions in the `README`, so that people know you officially endorse the bower install. Something as simple as:

```
Install through bower by running `bower install jquery-cycle2`
```

should do the trick.

A few questions:

There are a lot of files in the `build` folder alongside the main file. Are they plugins, or separate pieces of the core? I think it's typical for the `build` folder to have **only** those things that you need to run the plugin. If those other `min` files aren't plugins, you should consider moving them out of that build folder.

A common pattern is to have a `tmp` folder which is then referenced to make the final build. You can keep the repository clean by `.gitignore`-ing that `tmp` folder. And, finally, `grunt-contrib-clean` can be used to wipe the `tmp` folder before every build, to ensure you're only using the latest stuff.

If they are plugins, then I'd maybe suggest making it more organized by putting them in a nested folder. Maybe `build/plugins`. This is just my personal philosophy here, but it seems best to me that it should be dead-simple to install this thing; when people open `build` they shouldn't have to think about which file(s) they need. When I first opened it up, I at first wasn't even sure if there was a fully built script in there.

Those details aside, you did a great job. Thanks again!

**Comment by malsup** [comment]
You make a good point, James.  All of the files in the build folder are output of the build process (grunt), but for 99% of users the only file they need is jquery.cycle2.min.js.  Some of the others files are baked into that file, but exist in case you want to piece together your own smaller version (ie: jquery.cycle.core.js + jquery.cycle.pager.js).  Other files provide extra functionality that isn't baked into the main distribution.

I'll have another go at the organization when I get a chance.

**Comment by malsup** [comment]
Also, I'll update the README as well.

**Comment by jamesplease** [comment]
Cool, @malsup. Thanks again. If you do end up having plugins in the build folder (or a nested directory within build), you should put a little write up about them in the `README`, I think, just to eliminate any possible confusion. Something like,

---

### Installation

Include `build/cycle2.min.js` in your bundle. _(Be sure to load it after `jQuery`!)_

### Plugins

Also in the `build` folder are numerous plugins. Include them after the core script to enhance the functionality of `cycle2`. For more on what these plugins do, reference **the docs**.

---

**Comment by malsup** [comment]
Updated the build structure and README.

**Comment by jamesplease** [comment]
:+1: Looks great.

**Comment by alancwoo** [comment]
Apologies for digging up an old issue, but it seems relevant to post to this issue - I tried installing cycle via bower today: `bower install jquery-cycle2` as mentioned in the docs, which didn't work:

> Registry returned 404 for GET on https://registry.npmjs.org/jquery-cycle2

Searching npmjs, I found only this repackaged 3rd party version, oddly enough, created yesterday: https://github.com/benesch/jquery-cycle

Or am I mistaken that the other `jquery-cycle2` was never official and may have sometime recently been removed? In this case, the README should be updated.
