### ISSUE TITLE
Update html inside cycle2

### ISSUE THREAD

**Issue by anteksiler** [malsup/cycle2#184]
I am using a button which triggers a jQuery function inside cycle2.

The function simply changes the text inside the slides. The DOM is updated but I cannot see on the browser.

**Comment by programmin1** [comment]
What about stop, destroy, re-initialize? I agree there could be an easier solution though.

**Comment by mikila85** [comment]
none of these works for me. i'm trying to add $("#mySlideshow").attr("data-cycle-pause-on-hover","true");
it must be done after .cycle() first initialize, with attr change and cant seem to find a way to make it reload the changes from the dom (new attr)
tried the stop, destroy, reinit, cycle()...nothing worked.

**Comment by programmin1** [comment]
@mikila85  That is technically not this bug. Try stop, destroy, cycle(options). Are you trying to workaround this bug? https://github.com/malsup/cycle2/issues/192

**Comment by mikila85** [comment]
well doing cycle(options) is not an option for me, i cant input the options in java, i need it to reRead the attributes again, i change the dom attributes (options) with for example to add pause on hover:   $("#mySlideshow").attr("data-cycle-pause-on-hover","true");
i think its a bug because reinit should reread the attributes as well, Surely Destroy and cycle again should! 

if you change the attr and the start the slideshow it gets the change, but after the first run of the slides, any change of the attributes will not be recieved.

*workarround?,  theres a use in data() that reads the attributes but i cant seem to find where why its not updating from the dom on destroy amd cycle again.  no success so far, just seeing them pass first time. i been all over the code with breakpoints and tried changing everything i find that might do the trick and cant figure out why the attributes are being read only once :( please help.

**Comment by mikila85** [comment]
its not a bug on the code!, it is caused by jquery! The .data() call not only retrieves data attributes it also attempts to evaluate/parse the attributes. So with an attribute like data-myjson='{"hello":"world"}' when retrieved via .data() will return an Object while retrieval via .attr() will return a string. Since .data() does extra processing jQuery stores the results of attribute evaluation in $.cache !!!, now i'm looking for a way to clear the data cache or make it nocache.. but atleast the source is identified :), if i find a correction i'll post, and if anyone got an idea on how i can fix this before i post a solution please help me get there faster. thank you :)

**Comment by mikila85** [comment]
the destroy function has: opts.container.removeData( 'cycle.opts' );
its just not working, cant seem to fix it :(

**Comment by programmin1** [comment]
There may be a problem in that cycle({...}) is expecting integers for many options, and if you are getting attr() of an element it will return string. Try multiplying by one.

**Comment by mikila85** [comment]
i think you miss understood the problem. reread it. I use cycle() with no options included!, the options are drawn out and updated from the container's attributes.

**Comment by programmin1** [comment]
What happens when you destroy, then cycle{...options...} ? Reinit with attributes might have a bug, at least when I tried it seems some options are expecting numbers not string (like attr).
