### ISSUE TITLE
cycle2 js initialisation failing, no errors

### ISSUE THREAD

**Issue by marissajmc** [malsup/cycle2#312]
Hello,

I want to use js to initialise cycle2, but nothing happens when I click the prev/next buttons. The only console log is <pre>[cycle2] --c2 init--</pre> and there are no errors. I tried to log 'cycle-initialized' and 'cycle-before' events but these don't run.

Any ideas?

Demo:
http://jsfiddle.net/mjcookson/KJjK8/6/

**Comment by malsup** [comment]
When you use the class "cycle-slideshow" the slideshow is automatically initialized by C2.  Since you have no metadata attributes on the slideshow, C2 uses the defaults (and finds no slides).  A slideshow cannot be initialized a second time without first destroying it.  So you have two options.

1.) Use a different classname for your slideshow.  (http://jsfiddle.net/KJjK8/8/)
2.) Destroy the slideshow, then initialize it. (http://jsfiddle.net/KJjK8/9/)
