### ISSUE TITLE
Basic Slideshow not working in Firefox

### ISSUE THREAD

**Issue by j8kerussell** [malsup/cycle2#378]
Hi,
First time user here. I followed steps and added jquery script and cycle2 script to header and then just copied and pasted the "getting started" code in. Works fine in Safari and Chrome, but not able to get it to work in firefox. Just showing up as 4 images vertically lined up. Any ideas?

**Comment by SpeakDesign** [comment]
I am getting the same thing, Hope someone can answer this. It fails on all browsers for me.

**Comment by malsup** [comment]
Please post a link or create a jsfiddle that demonstrates the problem.

**Comment by SpeakDesign** [comment]
Malsup, the man the myth the legend. Thank you so much, I fixed the error and it is working like the champ it is.

**Comment by Chevron7** [comment]
How was this issue resolved?

**Comment by j8kerussell** [comment]
I'm not sure how SpeakDesign solved the problem, but for me, I'm putting the cycle2 slideshow on my squarespace and when I was going to preview my design, squarespace was defaulting the page to an https:// and cycle2 doesn't appear to work when it's being viewed in HTTP SECURE. At least for me, it works when I just use http://website.com

**Comment by malsup** [comment]
Cycle doesn't care what protocol your page loads over.  As long as jQuery and the cycle scripts load, that's all that matters.

**Comment by j8kerussell** [comment]
Hey Malsup,
I get what you're saying, but check out my homepage: 
https://therussellbrothers.com versus http://therussellbrothers.com

This doesn't make sense to me. Maybe I'm doing something wrong.

**Comment by malsup** [comment]
You might want to check your config.  When I try to load that site, Chrome warns me:

You attempted to reach therussellbrothers.com, but instead you actually reached a server identifying itself as *.squarespace.com. This may be caused by a misconfiguration on the server or by something more serious. An attacker on your network could be trying to get you to visit a fake (and potentially harmful) version of therussellbrothers.com.
You should not proceed, especially if you have never seen this warning before for this site.

**Comment by SpeakDesign** [comment]
My solution was found by Malsup and I believe it was a JavaScript error being resolved that fixed it for me.

**Comment by Chevron7** [comment]
## Well, I am about to give up on cycle2 as I am having more problems with Firefox ONLY. I tried to fix the slideshow div width an height using css and <div class="cycle-slideshow" data-cycle-auto-height=false> in Test but its not working.
