### ISSUE TITLE
Command callbacks

### ISSUE THREAD

**Issue by ShintoTuna** [malsup/cycle2#388]
Hello 
I'm in need of a way to use a callback after 'goto' command has finished. I cant use events because if goto is triggered for active slide it wont fire the event.  Is there any way to do so? 

Something like:
$( '#categories' ).cycle('goto', 3, function() {
    alert('done');
});

**Comment by albell** [comment]
Well, `goto` doesn't really "finish" exactly, because it doesn't have a duration. It's a command that can trigger a transition, but not the transition itself.

You can probably still use events. Listen for `cycle-after`, then run your named callback function.

To handle the "goto current slide" case, where no transition happens, just run a check to see if the target slide index matches the current slide index. If it does, don't bother with `goto` command, and just execute the named callback.
