### ISSUE TITLE
ScrollHorz Question

### ISSUE THREAD

**Issue by Minasokoni** [malsup/cycle2#81]
I have a strange issue using jquery cycle. But I also think it might be css related. What happens is on transition to the next slide the incoming slide stops about a quarter of the way, then snaps to the end of the screen completing the scrollHorz transition that cycle2 uses. To get rid of the issue I have to set my screen with pretty wide to stop it from happening. I should also include that the slides are scaled to the browser and it only happens in one direction when the slides are moving right to left. Its like the z-index change is happening before it moves to the next slide.

![Untitled-2](https://f.cloud.github.com/assets/1010168/72786/cd9b44c8-6022-11e2-8da2-231cdaa51b34.jpg)

EDIT:

Fixed by scaling the containers to the browser window.

**Comment by SeanDKendle** [comment]
Actually, there seems to be a logic error in the zIndex stacking in the function "stackSlides":

// curr slide on top,  next slide beneath, and the rest in order to be shown
        $(curr).css('zIndex', opts.maxZ);

The "curr" slide at this point is _not_ the incoming slide, but outgoing slide.  What seems to be happening is that it's setting the "previous slide" (in the image above) to the highest z-index, then making the "incoming slide" that number -1.  That's what is causing what appears to be a "snap" effect.

I fixed this by changing the lines to read:

```
    // reset the zIndex for the common case:
    // next slide on top,  curr slide beneath, and the rest in order to be shown
    var i;
    var z = opts.maxZ - 2;
    var len = opts.slideCount;

    $(opts.slides[opts.currSlide]).css('zIndex', z);
```

@malsup, does that make sense to you?  Try that out, maybe.  It works for me!
